### ISSUE TITLE
img

### ISSUE THREAD

**Issue by sis92345** [sis92345/TIL#1]
![jsFunction](https://user-images.githubusercontent.com/68282095/105045930-ce2e9980-5aab-11eb-864e-df49c8135198.jpg)

**Comment by sis92345** [comment]
[Mac 개발환경 설정.md](https://github.com/sis92345/TIL/files/7210700/Mac.md)

**Comment by hojin7769** [comment]
이건 뭐죠?

**Comment by sis92345** [comment]
이미지 업로드 시키는거 ㅋㅋㅋ 여기에 이미지 드래그 시키면 md 향식으로 이미지 나옵니다!

**Comment by hojin7769** [comment]
ㅋㅋㅋㅋ \<\img\ src=''\> 이게 짱임 ㅅㄱ

**Comment by sis92345** [comment]
mark down으로 뽑아야해

**Comment by hojin7769** [comment]
<img src="https://avatars.githubusercontent.com/u/85658845?s=80&v=4" width="300px" height="300px">

**Comment by hojin7769** [comment]
이쁘지
